### ISSUE TITLE
[Bug]:  failed to save the data to cache, error: adapt.<locals>.update_cache_func() 

### ISSUE THREAD

**Issue by itjuba** [zilliztech/GPTCache#223] opened 2023-04-17 19:31 UTC
### Current Behavior

Hello ,  I was trying to run the following code from the doc  ([chat with GPT](https://gptcache.readthedocs.io/en/latest/bootcamp/openai/chat.html))) , but i am getting this message in console: 

 WARNING: failed to save the data to cache, error: adapt.<locals>.update_cache_func() takes 1 positional argument but 2 were given

### Expected Behavior

Cache save and update is expected

### Steps To Reproduce

```markdown
Code :


import time


def response_text(openai_resp):
    return openai_resp['choices'][0]['message']['content']

print("Cache loading.....")

# To use GPTCache, that's all you need
# -------------------------------------------------
from gptcache import cache
from gptcache.adapter import openai

cache.init()
cache.set_openai_key()
# -------------------------------------------------

question = "what's github"
for _ in range(2):
    start_time = time.time()
    response = openai.ChatCompletion.create(
      model='gpt-3.5-turbo',
      messages=[
        {
            'role': 'user',
            'content': question
        }
      ],
    )
    print(f'Question: {question}')
    print("Time consuming: {:.2f}s".format(time.time() - start_time))
    print(f'Answer: {response_text(response)}\n')

```
```


### Environment

```markdown
Env : Python 3.10.7,GPTCACHE v0.1.13
```

**Comment by SimFG** [comment] 2023-04-17 22:17
hi, @itjuba,  you can try to delete files in the current dir, like `map.txt`, `sqlite.db` `faiss.index`. This error is caused by interface adjustment.

**Comment by SimFG** [comment] 2023-04-17 22:45
@itjuba thank your feedback, i have found the reason. and it will be fixed, #224

**Comment by SimFG** [comment] 2023-04-17 22:58
update the latest version, `0.1.14`, it has been fixed

**Comment by itjuba** [comment] 2023-04-18 02:34
You rock ! @SimFG  Thank you

**Closed** 2023-04-18 02:34 UTC
