### ISSUE TITLE
[Feature]: Support huggingface transformers LLM model

### ISSUE THREAD

**Issue by Zjq9409** [zilliztech/GPTCache#335] opened 2023-05-11 09:13 UTC
### Is your feature request related to a problem? Please describe.

Can huggingface LLM model chat caching be support?

**Comment by SimFG** [comment] 2023-05-11 09:27
You can try to use the GPTCache api, a simple example like:
```
from gptcache.adapter.api import put, get, init_similar_cache

init_similar_cache()
put("hello", "foo")
print(get("hello"))
```

**Comment by SimFG** [comment] 2023-05-11 13:10
Yes, you can use the `LangChainLLMs`, like:
```
from gptcache.adapter.langchain_models import LangChainLLMs
from langchain.llms import OpenAI

langchain_openai = OpenAI(model_name="text-ada-001")
llm = LangChainLLMs(llm=langchain_openai)
answer = llm(prompt=question)
```

if you use the langchain, you can also use it like:
```
import langchain
from langchain.cache import GPTCache
from gptcache.adapter.api import init_similar_cache

langchain.llm_cache = GPTCache(init_func=lambda cache: init_similar_cache(cache_obj=cache))
```

**Comment by SimFG** [comment] 2023-05-12 03:10
@Zjq9409 If there isn't other question,  i will close the issue

**Comment by Zjq9409** [comment] 2023-05-12 09:33
```
from langchain.llms import HuggingFacePipeline
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline, AutoModelForSeq2SeqLM
from langchain import PromptTemplate, HuggingFaceHub, LLMChain
from langchain.llms import OpenAI
from langchain import PromptTemplate

from gptcache.adapter.langchain_models import LangChainLLMs
from gptcache.manager import get_data_manager, CacheBase, VectorBase
from gptcache import Cache
from gptcache.embedding import Onnx
from gptcache.processor.pre import get_prompt
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation

import time
import os
from transformers import AutoModel, AutoTokenizer

os.environ['HUGGINGFACEHUB_API_TOKEN'] = ''
model_id = 'google/flan-t5-base'
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForSeq2SeqLM.from_pretrained(model_id)
pipe = pipeline(
    "text2text-generation",
    model=model, 
    tokenizer=tokenizer, 
    max_length=100
)

local_llm = HuggingFacePipeline(pipeline=pipe)
llm_cache = Cache()
onnx = Onnx()
cache_base = CacheBase('sqlite')
vector_base = VectorBase('faiss', dimension=onnx.dimension)
data_manager = get_data_manager(cache_base, vector_base, max_size=10, clean_size=2)
llm_cache.init(
    pre_embedding_func=get_prompt,
    embedding_func=onnx.to_embeddings,
    data_manager=data_manager,
    similarity_evaluation=SearchDistanceEvaluation(),
)
question = "上海有什么好吃的"
before = time.time()
cached_llm = LangChainLLMs(llm=local_llm)
answer = cached_llm(prompt=question, cache_obj=llm_cache)
print(answer)
print("Read through Time Spent =", time.time() - before)

questions = [
    '上海有哪些好吃的地方',
    '上海有哪些好吃的美食',
    '上海的美食有什么',
    '上海有什么好玩的地方',
    '怎么还花呗'
]
for question in questions:
        before = time.time()
        answer = cached_llm(prompt=question, cache_obj=llm_cache)
        print(f'Question: {question}')
        print(answer)
        print("Cache Hit Time Spent =", time.time() - before)
```


```
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Read through Time Spent = 0.35816311836242676
Question: 上海有哪些好吃的地方
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Cache Hit Time Spent = 0.14227008819580078
Question: 上海有哪些好吃的美食
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Cache Hit Time Spent = 0.13515877723693848
Question: 上海的美食有什么
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Cache Hit Time Spent = 0.13379120826721191
Question: 上海有什么好玩的地方
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Cache Hit Time Spent = 0.14519858360290527
Question: 怎么还花呗
上海有什么好吃的 上海是一个美食之都,有很多好吃的选择。以下是一些可以尝试的:

1. 小笼包:小笼包是上海最有名的美食之一。可以去著名的“朱家角小笼包”品尝。

2. 生煎包:生煎包是上海另一种著名的美食。可以去“沈大成”或者“老正兴”品尝。

3. 红烧肉:红烧肉是上海传统的名菜之一。可以去“红烧肉大师”
Cache Hit Time Spent = 0.14341497421264648

```

Why is the last question is cached?

**Comment by SimFG** [comment] 2023-05-12 09:41
because the `onnx.to_embeddings` is the english embedding model, you need a chinese embedding model, reference: #317

**Comment by Zjq9409** [comment] 2023-05-13 07:23
Does it support huggingface conversation caching？

**Comment by SimFG** [comment] 2023-05-15 02:34
I think it can, you can try it. because the langchain has handled the conversation situation.

**Comment by Zjq9409** [comment] 2023-05-16 13:46
```
import time
import requests
from typing import Optional, List, Dict, Mapping, Any

import langchain
from langchain.llms.base import LLM


class ChatGLM(LLM):
    url = "http://www.baifachuan.com:8004/v1/chat/completions"
    chat_history = []

    @property
    def _llm_type(self) -> str:
        return "chatglm"

    def _construct_query(self, prompt: str) -> Dict:
        self.chat_history.append({"role": "user", "content": prompt})
        query = {
            "model": "gpt-3.5-turbo",
            "messages": self.chat_history
        }
        return query

    @classmethod
    def _post(cls, url: str,
              query: Dict) -> Any:
        _headers = {"Content_Type": "application/json", "Authorization": "Bearer token1"}
        with requests.session() as sess:
            resp = sess.post(url,
                             json=query,
                             headers=_headers,
                             timeout=60)
        return resp

    def _call(self, prompt: str,
              stop: Optional[List[str]] = None) -> str:
        """_call
        """
        # construct query
        query = self._construct_query(prompt=prompt)

        # post
        resp = self._post(url=self.url,
                          query=query)

        if resp.status_code == 200:
            resp_json = resp.json()
            self.chat_history.append(resp_json['choices'][0]['message'])
            predictions = resp_json['choices'][0]['message']['content']
            return predictions
        else:
            return "请求模型"

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        """Get the identifying parameters.
        """
        _param_dict = {
            "url": self.url
        }
        return _param_dict


if __name__ == "__main__":
    llm_cache = Cache()
    cache_base = CacheBase('sqlite')
    vector_base = VectorBase('faiss', dimension=huggingface.dimension)
    data_manager = get_data_manager('sqlite', vector_base, max_size=10, clean_size=2)
    llm_cache.init(
        pre_embedding_func=get_prompt,
        embedding_func=huggingface.to_embeddings,
        data_manager=data_manager,
        similarity_evaluation=SearchDistanceEvaluation(),
    )
    llm = ChatGLM()
    while True:
        human_input = input("Human: ")

        begin_time = time.time() * 1000
        # 请求模型
        response = llm(human_input, stop=["you"])
        end_time = time.time() * 1000
        used_time = round(end_time - begin_time, 3)
        logging.info(f"chatGLM process time: {used_time}ms")

        print(f"ChatGLM: {response}")
```
The above cache has no effect. need use ConversionChain to set?

**Comment by SimFG** [comment] 2023-05-17 07:04
@Zjq9409 From the error stack, can you try to run directly the llm, like:
```
llm(prompt="你好")
```

**Comment by Zjq9409** [comment] 2023-05-17 09:52
still report the same problem.

**Comment by SimFG** [comment] 2023-05-17 09:58
@Zjq9409 if there is the same problem when you run the code:
```
llm(prompt="你好")
```
Looks like it should not be caused by GPTCache and it's caused the llm model.

**Comment by Zjq9409** [comment] 2023-05-17 12:21
Actually, the usage method is: `llm._call("你好")` , but i need to combine with `LangChainLLMs` to use Cache, right?

**Comment by SimFG** [comment] 2023-05-17 12:25
when the cache is empty, it will call the origin llm model to get the answer, and then the answer will be saved to cache. In the next time, you will get the answer from the cache when you request a similar request.

**Comment by SimFG** [comment] 2023-05-22 07:18
@Zjq9409 Is your problem solved? If you want to use the huggingface transformers LLM model, you can use the GPTCache api. If you encounter other problems, you can open a new issue.

**Closed by SimFG** 2023-05-22 07:18 UTC

**Comment by iunique** [comment] 2023-05-26 08:28
I also encountered this problem, how to solve this problem

**Comment by SimFG** [comment] 2023-05-26 09:01
@iunique hi, you can open a new issue and describe your problem.
