### ISSUE TITLE
[Bug]: GPTCache similarity caching code example encountered an error during execution

### ISSUE THREAD

**Issue by kennethleungty** [zilliztech/GPTCache#301] opened 2023-04-27 04:10 UTC
### Current Behavior

This is an issue relating to the integration of GPTCache with LangChain

```
import os
import time
import gptcache
from gptcache.processor.pre import get_prompt
from gptcache.manager.factory import get_data_manager
from langchain.cache import GPTCache, SQLiteCache
from gptcache.manager import get_data_manager, CacheBase, VectorBase
from gptcache import Cache
from gptcache.embedding import Onnx
from gptcache.similarity_evaluation.distance import SearchDistanceEvaluation
from langchain.llms import OpenAI
import langchain
import openai
from decouple import config

os.environ["OPENAI_API_KEY"] = config("OPENAI_API_KEY")
openai.api_base = config("OPENAI_API_BASE")

llm = OpenAI(model_name="text-davinci-002", n=1, best_of=1)
i = 0
file_prefix = "data_map"
llm_cache = Cache()

def init_gptcache_map(cache_obj: gptcache.Cache):
global i
cache_path = f'{file_prefix}_{i}.txt'
onnx = Onnx()
cache_base = CacheBase('sqlite')
vector_base = VectorBase('faiss', dimension=onnx.dimension)
data_manager = get_data_manager(cache_base, vector_base, max_size=10, clean_size=2)
cache_obj.init(
pre_embedding_func=get_prompt,
embedding_func=onnx.to_embeddings,
data_manager=data_manager,
similarity_evaluation=SearchDistanceEvaluation(),
)
i += 1

langchain.llm_cache = GPTCache(init_gptcache_map)

llm("Tell me a joke")
`
```

error:
Traceback (most recent call last): File "D:\chat-main\tt.py", line 43, in <module> llm("Tell me a joke") File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 246, in __call__ return self.generate([prompt], stop=stop).generations[0][0].text ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 161, in generate llm_output = update_cache( ^^^^^^^^^^^^^ File "D:\chat-main\venv\Lib\site-packages\langchain\llms\base.py", line 51, in update_cache langchain.llm_cache.update(prompt, llm_string, result) File "D:\chat-main\venv\Lib\site-packages\langchain\cache.py", line 255, in update return adapt( ^^^^^^ File "D:\chat-main\venv\Lib\site-packages\gptcache\adapter\adapter.py", line 22, in adapt embedding_data = time_cal( ^^^^^^^^^ File "D:\chat-main\venv\Lib\site-packages\gptcache\__init__.py", line 25, in inner res = func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "D:\chat-main\venv\Lib\site-packages\gptcache\embedding\onnx.py", line 58, in to_embeddings ort_outputs = self.ort_session.run(None, ort_inputs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\Program Files (x86)\Python311\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run return self._sess.run(output_names, input_feed, run_options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int32)) , expected: (tensor(int64))

**Comment by SimFG** [comment] 2023-04-27 05:08
The problem seems to be an onnx version problem, I will check it out

**Comment by wxywb** [comment] 2023-04-27 07:59
It seems the type of tokens after tokenizer is np.int32 instead of np.int64. A new PR make sure the input type is np.in64  should fix this. https://github.com/zilliztech/GPTCache/pull/302

**Comment by xusheng-gong** [comment] 2023-04-27 09:32
I met same problem

**Comment by SimFG** [comment] 2023-04-27 09:45
@xusheng-gong We try to reproduce this problem, but without success. you can try to install the latest development version to see if the problem is solved
```
# clone GPTCache repo
git clone -b dev https://github.com/zilliztech/GPTCache.git
cd GPTCache

# install the repo
pip install -r requirements.txt
python setup.py install
```

**Comment by kennethleungty** [comment] 2023-04-28 03:25
Hi @SimFG, are you able to recreate the problem when using LangChain? It seems likely the ONNX issue lies in the GPTCache version (0.1.18) that is integrated with LangChain.

**Comment by SimFG** [comment] 2023-04-28 03:48
@kennethleungty i will try, can you help me try to use the `dev` version to make sure the bug has been fixed

**Comment by kennethleungty** [comment] 2023-04-28 04:39
Hi @SimFG, thank you, yup I have managed to try it out and it seems mostly to work. Some points:

1. In the setup.py, would be great to incorporate the encoding parameter when reading the README markdown because I encountered `charmap` probs when first running the `python setup.py install` command. i.e.,:

```
with open("README.md", "r", encoding='utf-8') as fh:
    long_description = fh.read()
```

2. It is now able to generate the cache and vectorstore, though I came across this warning message each time I run it:
`22916 - adapter.py-adapter:154 - WARNING: failed to save the data to cache, error: _update_cache_callback() got an unexpected keyword argument 'prompt'`

Any issue with the above warning?

**Comment by kennethleungty** [comment] 2023-04-28 04:42
To add on, I just retried using a LangChain agent, and got a slightly different ONNX error message this time round: `InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 698 Expected: 512
 Please fix either the inputs or the model.`

**Comment by kennethleungty** [comment] 2023-04-28 04:43
I also actually just reran with the LangChain agent and got a slightly different error message this time round:

`InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: token_type_ids for the following indices
 index: 1 Got: 698 Expected: 512
 Please fix either the inputs or the model.`
 
FYI I have been setting max_tokens for my LLM to be 512

**Comment by SimFG** [comment] 2023-04-28 04:44
@kennethleungty  you can update the `langchain` latest version, it's a compatibility issues
`22916 - adapter.py-adapter:154 - WARNING: failed to save the data to cache, error: _update_cache_callback() got an unexpected keyword argument 'prompt'`

**Comment by kennethleungty** [comment] 2023-04-28 04:47
ok sure, will note about the langchain version (currently 0.0.151 is down with other issues, so I have temporarily downgraded). In terms of the new error i.e., `InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT....`, I noticed that it does not appear when I do a simple query like 'tell me a joke', but has trouble when I try to cache the output from an agent that is coupled with vectorstore retrievalQA tools

**Comment by SimFG** [comment] 2023-04-28 04:52
@kennethleungty 
We will improve the code in langchain to reduce the possibility of compatibility issues. For the problem of onnx, we will check it out. If it is possible, can you provide some simple test code?

**Comment by kennethleungty** [comment] 2023-04-28 04:58
Sure, I have placed some of the key chunks of the code to show the setup of an agent along with 2 vectorstore RetrievalQA tools. P.S. only the key chunks are placed here, not the full code

```
tnc_db = FAISS.load_local('../source_data/demos/terms_and_conditions/vectorstore', embeddings)
phone_db = FAISS.load_local('../source_data/demos/phone_manual/vectorstore', embeddings)

# Giving just one example of the vectorstore loading
phone_dbqa = RetrievalQA.from_chain_type(llm=llm, 
                                         chain_type="stuff",
                                         retriever=phone_db.as_retriever(search_kwargs={"k":3}), 
                                         return_source_documents=True,
                                         chain_type_kwargs=chain_type_kwargs)

tools = [
    Tool(
        name = "Phone Manual QA System",
        func=phone_dbqa, # return source documents (don't include .run)
        description="useful for when you need to answer questions about specifications and information about the phone, \
                    since this information source is based on a phone manual. Input should be a fully formed question.",
    ),
    Tool(
        name = "T&C QA System",
        func=tnc_dbqa, # return source docs
        description="useful for when you need to answer questions about the terms and conditions of a banking credit card. Input should be a fully formed question.",
    ),
]

output_parser = CustomOutputParser()

# LLM chain consisting of the LLM and a prompt
llm_chain = LLMChain(llm=llm_agent, prompt=prompt)
tool_names = [tool.name for tool in tools]

agent = LLMSingleActionAgent(
            llm_chain=llm_chain, 
            output_parser=output_parser,
            stop=["\nObservation:"], 
            allowed_tools=tool_names
)

agent_executor = AgentExecutor.from_agent_and_tools(agent=agent, 
                                                    tools=tools, 
                                                    verbose=True)

query = 'How to turn on data roaming? What is the cashback benefit of my credit card?'

output = agent_executor.run({"input": query, 
                             "chat_history": chat_history})
```

**Comment by SimFG** [comment] 2023-04-28 05:11
@kennethleungty thank your feedback :)

**Comment by kennethleungty** [comment] 2023-04-28 05:12
I would think that the agent response to be cached is pretty long (much longer than the response obtained from the 'Tell me a joke' simple query), so that may have screwed the ONNX tokens up in some way

**Comment by xiaofan-luan** [comment] 2023-04-28 05:16
> I would think that the agent response to be cached is pretty long (much longer than the response obtained from the 'Tell me a joke' simple query), so that may have screwed the ONNX tokens up in some way

We are thinking of supporting LLM and reduce tokens by other modes. 
Feel free to give us contribution on new models

**Comment by SimFG** [comment] 2023-05-11 15:55
@kennethleungty now you can try to use the context processor to handle the long prompt, like:
```
from gptcache.processor.context.summarization_context import SummarizationContextProcess
from gptcache import cache

context_process = SummarizationContextProcess()
cache.init(
        pre_embedding_func=context_process.pre_process,
        ...
)
```
or selective context, like:
```
context_processor = SelectiveContextProcess()
```

**Comment by SimFG** [comment] 2023-05-12 03:12
More discussion will be in issue: #298

**Closed by SimFG** 2023-05-12 03:12 UTC
Labels: enhancement
